name: slm_model_detector
description: A Flutter app that detects phone model and assigns SLM from Hugging Face.
version: 1.0.0+1

environment:
  sdk: "^3.3.0"

dependencies:
  flutter:
    sdk: flutter
  device_info_plus: ^11.4.0
  http: ^0.13.6
  path_provider: ^2.1.2
  dio: ^5.4.0
  permission_handler: ^12.0.0+1

flutter:
  uses-material-design: true

  
